apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - port: ${APP_PORT}
    targetPort: ${APP_PORT}
    nodePort: ${APP_NODE_PORT}
